// ===== Especialistas =====
//
// Os perfis que o produto oferece como "quem está te ajudando": o que cada um
// sabe, o que entrega e como fala. Dado puro, quase cem linhas, no meio de um
// arquivo de telas.

import {
  Archive,
  Award,
  BadgeCheck,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Calculator,
  CircleAlert,
  Clock3,
  DollarSign,
  Eye,
  FileText,
  Filter,
  Globe2,
  GraduationCap,
  Handshake,
  Headphones,
  Layers,
  Lightbulb,
  ListTodo,
  LockKeyhole,
  Megaphone,
  MessageSquareText,
  Monitor,
  Palette,
  PanelsTopLeft,
  Rocket,
  Search,
  ShieldCheck,
  ShoppingBag,
  Sun,
  Target,
  TrendingUp,
  UserCog,
  UserRound,
  Users,
  WalletCards,
  Workflow,
} from "lucide-react";

export const specialistData = [
  [
    "Diretor",
    Bot,
    "Entende o pedido, envolve as áreas certas e consolida tudo.",
  ],
  ["Fundador", Rocket, "Transforma uma ideia em um negócio estruturado."],
  ["Estrategista", Target, "Analisa cenários, riscos e prioridades."],
  ["Consultor", BriefcaseBusiness, "Diagnostica e recomenda ações práticas."],
  ["Redator", FileText, "Cria e aprimora textos profissionais."],
  ["Negociador", Handshake, "Prepara argumentos, objeções e acordos."],
  ["Precificador", Calculator, "Estrutura preços, custos e margens."],
  ["Marketing", Megaphone, "Cria posicionamento, campanhas e conteúdo."],
  ["Vendas", TrendingUp, "Organiza prospecção e acompanhamento."],
  ["Atendimento", Headphones, "Ajuda a responder e cuidar de clientes."],
  ["Financeiro", WalletCards, "Interpreta os números que você informar."],
  ["Operações", Boxes, "Cria processos, rotinas e checklists."],
  ["Pessoas", UserCog, "Apoia cargos, entrevistas e onboarding."],
  ["Criador de Sites", Globe2, "Transforma um briefing em página utilizável."],
  [
    "Jurídico",
    BriefcaseBusiness,
    "Contratos, minutas, políticas e riscos legais.",
  ],
  ["TI", Monitor, "Sistemas, integrações, automações e segurança técnica."],
  ["Produto", Lightbulb, "Discovery, roadmap, backlog e lançamento."],
  ["Projetos", ListTodo, "Escopo, cronograma, riscos e acompanhamento."],
  [
    "Customer Success",
    UserRound,
    "Onboarding, retenção, churn e planos de sucesso.",
  ],
  ["Dados", Filter, "Indicadores, análises e decisões com evidências."],
  ["Logística", Boxes, "Estoque, fretes, prazos e supply chain."],
  ["Compras", ShoppingBag, "Cotações, fornecedores e suprimentos."],
  ["Administrativo", Archive, "Rotinas, controles e organização interna."],
  [
    "Comunicação",
    MessageSquareText,
    "Comunicação institucional e gestão de crise.",
  ],
  ["Design", Palette, "Identidade visual, briefings e direção de arte."],
  ["Conteúdo", FileText, "Planejamento editorial, pautas e materiais ricos."],
  ["Pesquisa", Search, "Pesquisas de mercado e de usuário bem estruturadas."],
  ["Inovação", Lightbulb, "Ideias, experimentos e validação com critérios."],
  ["Expansão", Globe2, "Novos mercados, filiais, franquias e canais."],
  ["Growth", TrendingUp, "Experimentos de aquisição, retenção e receita."],
  ["E-commerce", ShoppingBag, "Loja virtual, checkout, conversão e campanhas."],
  ["Marketplace", PanelsTopLeft, "Cadastro, reputação, buy box e anúncios."],
  ["Qualidade", BadgeCheck, "Padrões, auditorias e melhoria contínua."],
  ["Compliance", ShieldCheck, "Políticas, condutas e riscos regulatórios."],
  [
    "Segurança da Informação",
    LockKeyhole,
    "Acessos, backups, LGPD e incidentes.",
  ],
  ["Processos", Workflow, "Mapeamento, padronização e automação."],
  [
    "Contabilidade",
    Calculator,
    "Organização contábil e material para o contador.",
  ],
  ["Riscos", CircleAlert, "Matriz de riscos, mitigação e monitoramento."],
  ["ESG", Sun, "Práticas ambientais, sociais e de governança."],
  [
    "Treinamento",
    GraduationCap,
    "Trilhas de capacitação e educação corporativa.",
  ],
  ["Auditoria", Eye, "Verificações independentes e planos de correção."],
  [
    "Inteligência Competitiva",
    Search,
    "Concorrentes, preços e movimentos de mercado.",
  ],
  ["Fornecedores", Handshake, "Homologação, contratos, SLAs e desempenho."],
  ["Parcerias", Handshake, "Alianças, acordos e governança da relação."],
  [
    "Captação",
    DollarSign,
    "Pitch deck, unit economics e preparação para investidores.",
  ],
  ["Carreira", Rocket, "Plano de carreira, avaliações e negociação salarial."],
  ["Produtividade", Clock3, "Rotina, prioridades e foco no trabalho."],
  ["Reuniões", Users, "Pautas, condução e ata com encaminhamentos."],
  ["Apresentações", Layers, "Narrativa e conteúdo de slides."],
  [
    "Gestão de Stakeholders",
    Handshake,
    "Mapeamento de interessados e alinhamento de expectativas.",
  ],
  ["Liderança", Award, "Feedback, delegação e conversas difíceis."],
];
