// ===== O espaço de trabalho vazio, e as chaves onde ele mora =====
//
// `emptyDb` é o formato de um espaço recém-criado: toda coleção que o produto
// conhece, declarada uma vez. É ele que evita a tela quebrar em
// `db.contatos.map` quando alguém adiciona um módulo novo e esquece de criar a
// lista.
//
// As chaves de armazenamento vêm junto porque são a outra metade da mesma
// decisão: onde este objeto é gravado no navegador.

export const LEGACY_STORAGE_KEY = "seu-funcionario-v1";
export const ACTIVE_USER_KEY = "seu-funcionario-active-user";
export const STORAGE_PREFIX = "seu-funcionario-v2:";
export const AUTH_TOKEN_KEY = "seu-funcionario-auth-token";

export const emptyDb = {
  user: null,
  spaceKey: null,
  updatedAt: null,
  onboarding: false,
  selectedBusinessId: null,
  businesses: [],
  tasks: [],
  leads: [],
  appointments: [],
  products: [],
  orders: [],
  quotes: [],
  supplierRfqs: [],
  recurring: [],
  timeEntries: [],
  contacts: [],
  deliveryZones: [],
  vehicles: [],
  trips: [],
  developmentPlans: [],
  notifications: [],
  teams: [],
  projects: [],
  workNodes: [],
  objectives: [],
  dashboardConfigs: [],
  chatChannels: [],
  chatMessages: [],
  chatReadStates: [],
  bills: [],
  opportunities: [],
  meetings: [],
  boards: [],
  diagrams: [],
  whiteboards: [],
  workHours: null,
  memories: [],
  glossary: [],
  notes: [],
  flashcards: [],
  projectLinks: [],
  portfolioRisks: [],
  raci: [],
  agents: [],
  agentRuns: [],
  salesPipeline: null,
  transactions: [],
  financeSettings: {},
  taxProfile: { isMEI: false, dueDay: 20, cnpj: "", dasHistory: {} },
  documents: [],
  syncedBlocks: [],
  presentations: [],
  contentPlan: [],
  sheets: [],
  analyses: [],
  brainstorms: [],
  signatures: [],
  pixCharges: [],
  databases: [],
  processes: [],
  processCases: [],
  formResponses: [],
  publicForms: [],
  clientPortals: [],
  resourceProfiles: [],
  resourceAbsences: [],
  resourceAllocations: [],
  pricingModels: [],
  pricingScenarios: [],
  impactFactors: [],
  impactEntries: [],
  wikiPages: [],
  automations: [],
  sites: [],
  history: [],
  certificates: [],
  conversations: [],
  media: [],
  codeProjects: [],
  notebook: null,
  emailDrafts: [],
  customSpecialists: [],
  pluggedTools: [],
  selectedConversationId: null,
  journeys: {},
  preferences: {
    theme: "light",
    specialist: "Diretor",
    mode: "business",
    modeChosen: false,
  },
};
